---
    - name: Update and upgrade system packages
      apt:
        update_cache: yes
#        upgrade: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Install PHP and required modules
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
          - php-gd
          - php-curl
          - php-mbstring
        state: present

    - name: Clone DVWA repository
      git:
        repo: https://github.com/digininja/DVWA.git
        dest: /var/www/html/DVWA
        force: yes

    - name: Set permissions for DVWA
      file:
        path: /var/www/html/DVWA
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

#    - name: Copy DVWA configuration file
#      copy:
#        src: /var/www/html/DVWA/config/config.inc.php.dist
#        dest: /var/www/html/DVWA/config/config.inc.php
#        remote_src: yes

    - name: Copy DVWA configuration file
      copy:
        src: /etc/ansible/files/dvwa_config.php
        dest: /var/www/html/DVWA/config/config.inc.php
#        remote_src: yes

    - name: Copy Apache configuration file for DVWA
      copy:
        src: /etc/ansible/files/dvwa_apache.conf
        dest: /etc/apache2/sites-available/dvwa.conf
#        remote_src: yes

    - name: Enable DVWA site
      command: a2ensite dvwa.conf

    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted

    - name: Enable PHP mbstring module
      command: phpenmod mbstring

    - name: Enable Apache rewrite module
      command: a2enmod rewrite

    - name: Restart Apache again
      systemd:
        name: apache2
        state: restarted
