---
- name: Install pipx and Semgrep
  hosts: 192.168.1.130
  become: yes
  tasks:
    - name: Install pipx
      apt:
        name: pipx
        state: present
        update_cache: yes

    - name: Install Semgrep via pipx
      command: pipx install semgrep

    - name: Ensure pipx path is set
      command: pipx ensurepath
      register: ensurepath_output

    - name: Display pipx ensurepath result
      debug:
        msg: "{{ ensurepath_output.stdout }}"

    - name: Re-login the remote host (to refresh environment)
      command: "ssh ansible@192.168.1.130 'exit'"
      async: 60
      poll: 0

#    - name: Verify semgrep installation
#      command: semgrep --version
#      register: semgrep_version

#    - name: Show semgrep version
#      debug:
#        msg: "Semgrep version: {{ semgrep_version.stdout }}"
